=== Tyler-Zhou/Bamboo/src/ICP3/EDI/ICP.EDI.MapForce/IFCSUM_FYCW.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="IFCSUM_FYCW" targetNamespace="http://tempuri.org/IFCSUM_FYCW.xsd" xmlns:mstns="http://tempuri.org/IFCSUM_FYCW.xsd" xmlns="http://tempuri.org/IFCSUM_FYCW.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:msprop="urn:schemas-microsoft-com:xml-msprop" attributeFormDefault="qualified" elementFormDefault="qualified">
  <xs:annotation>
    <xs:appinfo source="urn:schemas-microsoft-com:xml-msdatasource">
      <DataSource DefaultConnectionIndex="0" FunctionsComponentName="QueriesTableAdapter" Modifier="AutoLayout, AnsiClass, Class, Public" SchemaSerializationMode="IncludeSchema" xmlns="urn:schemas-microsoft-com:xml-msdatasource">
        <Connections />
        <Tables />
        <Sources />
      </DataSource>
    </xs:appinfo>
  </xs:annotation>
  <xs:element name="IFCSUM_FYCW" msdata:IsDataSet="true" msdata:UseCurrentLocale="true" msprop:Generator_DataSetName="IFCSUM_FYCW" msprop:Generator_UserDSName="IFCSUM_FYCW" msprop:EnableTableAdapterManager="true">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="EDI" msprop:Generator_UserTableName="EDI" msprop:Generator_RowDeletedName="EDIRowDeleted" msprop:Generator_TableClassName="EDIDataTable" msprop:Generator_RowChangedName="EDIRowChanged" msprop:Generator_RowClassName="EDIRow" msprop:Generator_RowChangingName="EDIRowChanging" msprop:Generator_RowEvArgName="EDIRowChangeEvent" msprop:Generator_RowEvHandlerName="EDIRowChangeEventHandler" msprop:Generator_TablePropName="EDI" msprop:Generator_TableVarName="tableEDI" msprop:Generator_RowDeletingName="EDIRowDeleting">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="EDIDATA" msprop:Generator_UserColumnName="EDIDATA" msprop:Generator_ColumnPropNameInRow="EDIDATA" msprop:Generator_ColumnVarNameInTable="columnEDIDATA" msprop:Generator_ColumnPropNameInTable="EDIDATAColumn" type="xs:string" minOccurs="0" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Tyler-Zhou/Bamboo/src/ICP3/EDI/ICP.EDI.FileManager/FYCW/IFCSUM_FYCW.xml
<?xml version="1.0" encoding="UTF-8"?>
<IFCSUM_FYCW xmlns="http://tempuri.org/IFCSUM_FYCW.xsd" xsi:schemaLocation="http://tempuri.org/IFCSUM_FYCW.xsd D:/Project/ICP2005/LongWin.EDI/LongWin.EDI.FileManager/IFCSUM_FYCW.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <EDI>
    <EDIDATA>00:IFCSUM:MANIFEST:2:TOP:POSASZ:201007291028'</EDIDATA>
  </EDI>
  <EDI>
    <EDIDATA>10::HATSU COURAGE::.0627E::::20100717:CNYTN:YANTIAN:::'</EDIDATA>
  </EDI>
  <EDI>
    <EDIDATA>11:CSCL:中海集装箱运输股份有限公司'</EDIDATA>
  </EDI>
  <EDI>
    <EDIDATA>12:CHNJYTNLAX111756::::::CNYTN:YANTIAN:CY-CY:C:20100716::::YTNLAX111756::19328:::::LOS ANGELES,CAM/BL'</EDIDATA>
  </EDI>
  <EDI>
    <EDIDATA>13:USLAX:LOS ANGELES,CA:USLAX:LOS ANGELES,CA:USLAX:LOS ANGELES,CA:CNCAN:GUANGZHOU:11'</EDIDATA>
  </EDI>
  <EDI>
    <EDIDATA>16:TOPSHIPPINGCN:TOP SHIPPING LOGISTICS CO.,LIMITED  22/F, A Bldg., Aerospace Skyscraper No. 4019, Shennan Road, Futian District, Shenzhen, china::86755 3395 8231:86755 3395 8201'</EDIDATA>
  </EDI>
  <EDI>
    <EDIDATA>17:COLA-LA:CITY OCEAN INTERNATIONAL INC., (LOS ANGELES OFFICE)  17890 CASTLETON ST.#205  CITY OF INDUSTRY,CA91748::626 810 0261:626 810 0251'</EDIDATA>
  </EDI>
  <EDI>
    <EDIDATA>18:COLA-LA:CITY OCEAN INTERNATIONAL INC., (LOS ANGELES OFFICE)  17890 CASTLETON ST.#205  CITY OF INDUSTRY,CA91748::626 810 0261:626 810 0251'</EDIDATA>
  </EDI>
  <EDI>
    <EDIDATA>19::'</EDIDATA>
  </EDI>
  <EDI>
    <EDIDATA>21:TOPSHIPPINGCN:TOP SHIPPING LOGISTICS CO.,LIMITED  22/F, A Bldg., Aerospace Skyscraper No. 4019, Shennan Road, Futian District, Shenzhen, china::86755 3395 8231:86755 3395 8201'</EDIDATA>
  </EDI>
  <EDI>
    <EDIDATA>22:COLA-LA:CITY OCEAN INTERNATIONAL INC., (LOS ANGELES OFFICE)  17890 CASTLETON ST.#205  CITY OF INDUSTRY,CA91748::626 810 0261:626 810 0251'</EDIDATA>
  </EDI>
  <EDI>
    <EDIDATA>23:COLA-LA:CITY OCEAN INTERNATIONAL INC., (LOS ANGELES OFFICE)  17890 CASTLETON ST.#205  CITY OF INDUSTRY,CA91748::626 810 0261:626 810 0251'</EDIDATA>
  </EDI>
  <EDI>
    <EDIDATA>24:::::'</EDIDATA>
  </EDI>
  <EDI>
    <EDIDATA>25:::::'</EDIDATA>
  </EDI>
  <EDI>
    <EDIDATA>41:1::413::CTNS:6787.00000::66.97000:'</EDIDATA>
  </EDI>
  <EDI>
    <EDIDATA>44:N/M'</EDIDATA>
  </EDI>
  <EDI>
    <EDIDATA>47:SHIPPER'S LOAD COUNT &amp; SEAL(1*  40HQ) CONTAINER S.T.C.    CY-CY  ACCEN'</EDIDATA>
  </EDI>
  <EDI>
    <EDIDATA>47:T TABLES  COMM:FAK  HB/L:GZLAXJG0230  SCAC:CTYO  NO WOOD PACKAGING MAT'</EDIDATA>
  </EDI>
  <EDI>
    <EDIDATA>47:ERIAL IS   USED IN THE SHIPMENT'</EDIDATA>
  </EDI>
  <EDI>
    <EDIDATA>51:1:TGHU9578039:K312691:40HQ:F:413:6787.00000::66.97000::::::'</EDIDATA>
  </EDI>
  <EDI>
    <EDIDATA>99:21'</EDIDATA>
  </EDI>
</IFCSUM_FYCW>
